[tool.ruff]
line-length = 120
target-version = "py311"
exclude = ["notebooks"]

[tool.ruff.lint]
select = ["E", "F"]
ignore = ["E501"]

[tool.ruff.lint.per-file-ignores]
"src/train.py" = ["E402"]

[tool.pytest.ini_options]
testpaths = ["tests"]
pythonpath = ["."]
filterwarnings = ["ignore::DeprecationWarning"]

[tool.poetry]
package-mode = false

[tool.poetry.dependencies]
python = "^3.11"
streamlit = "1.41.1"
plotly = "5.24.1"
pandas = "2.2.3"
numpy = "1.26.4"
requests = "2.32.3"
boto3 = "1.35.90"