FROM python:3.11-slim
ENV PYTHONDONTWRITEBYTECODE=1 PYTHONUNBUFFERED=1 PYTHONPATH=/app
WORKDIR /app
COPY requirements-serve.txt requirements-train.txt ./
RUN pip install --no-cache-dir -r requirements-train.txt
COPY src ./src
CMD ["python", "-m", "src.train"]
